### ISSUE TITLE
Can't sneak right click Petal Apothecary in school to remove items

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Academy#271]
If you accidentally put the wrong items in, you can't get them back out without restarting the school.

**Comment by salimfadhley** [comment]
I was able to fill the apothecary but I was only able to add one of each petal type and I couldn't add the seeds. Game over! :-(

**Comment by royblokker** [comment]
> If you accidentally put the wrong items in, you can't get them back out without restarting the school.

I have the exact same problem

**Comment by aaronhowser1** [comment]
Is this still true in 1.2.0 @salimfadhley @royblokker ?

**Comment by andywyldebag** [comment]
Same problem here    hoping i can get a fix for it since I've made this world a server

**Comment by royblokker** [comment]
> Is this still true in 1.2.0 @salimfadhley @royblokker ?

Yes

**Comment by LowLife007** [comment]
Fixed it with. /reset_school

**Comment by royblokker** [comment]
> Fixed it with. /reset_school

Then you have to do it al over again?

**Comment by Dr69onS6mur6i** [comment]
Yes. I just started working with this mod and I'm having this issue as well. The /reset_school command resets everything. It fixed my issue with some quests hanging out in the upper left of the screen, but I'm still having a problem with the Botanica area where it asks you to put the petals and seeds into the apothecary. It only lets me put in one item in on each side of the apothecary so after I put in the petals I can't put in the seeds.

**Comment by aaronliu0130** [comment]
@aaronhowser1 I had the same issue BUT I solved it by first removing the water with a water bucket. Then I successfully got my wrong items out.

**Comment by dcitrigno-DJLC** [comment]
I also have this problem however if you stand on the apothocary (spelling) and hit q twice for brown 1 for grey and once for red it's correct but it still won't allow the seeds to be placed, every time  i hit Q it just jumps back into my hand there is definately a problem with the either the scripts for the Academy or the ones to do with Botania to be fair the version in the pack is r1.10-362, possibly the problem i may just look to find a newer version of the mod and install it directly into MC and see if it still does this little trick.

**Comment by ff2009** [comment]
This will probably never be fix but is still happening in version 1.4.0.
